# -*- coding: utf-8 -*-
"""Virtual Try-On System (Computer Vision)_Exam Assignemnt_Ashiq Rahman Chowdhury.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mkuHf-AWVc5INh7Dxva2NSsGBICvkkdx

🧠 Exam Assignment: Virtual Try-On System (Computer Vision)
🎯 Objective
Build a Virtual Try-On system where a user can upload an image and digitally modify clothing using Computer Vision + AI APIs.

🧩 Problem Statement
Create an application with the following flow:
Upload an image
User selects:
Upper body OR
Lower body
Based on selection:
Segment the selected body part
Apply AI-based inpainting to change clothing
Display the final output image

⚙️ Technical Requirements
🔹 Image Processing
Preprocess uploaded image (resize, normalize if needed)
🔹 Segmentation
Use any method:
Pretrained model OR external API
Output should isolate:
Upper clothing OR lower clothing region

🔹 Inpainting (Important)
You must use an external AI API for inpainting.
Suggested platforms:
Hugging Face
Segmind
👉 You need to explore documentation and implement it yourself.

🖥️ UI Requirement
Minimum:
Image upload
Selection option:
Upper / Lower
Button: “Try On”
Output image display
Optional (Bonus):
Build UI using:
Gradio
Streamlit

🔁 Expected Pipeline
Upload Image → Segment Body Part → Apply Inpainting → Show Result

---
> ⚠️ **Runtime:** Set Runtime → Change runtime type → **T4 GPU** for best performance

## Step 1 — Install Dependencies
"""

# Install all required packages
!pip install -q transformers accelerate
!pip install -q diffusers
!pip install -q gradio
!pip install -q huggingface_hub
!pip install -q opencv-python-headless
!pip install -q scipy
!pip install -q Pillow matplotlib numpy requests

print('✅ All packages installed successfully!')

"""## Step 2 — Import Libraries"""

import numpy as np
import requests
import io
import os
import cv2
import warnings
warnings.filterwarnings('ignore')

from PIL import Image, ImageFilter, ImageDraw
import matplotlib.pyplot as plt
import matplotlib.patches as patches

import torch
from transformers import (
    SegformerImageProcessor,
    SegformerForSemanticSegmentation
)
from scipy.ndimage import binary_dilation

import gradio as gr

# Check GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'✅ Libraries loaded | Device: {device}')
if device == 'cuda':
    print(f'   GPU: {torch.cuda.get_device_name(0)}')

"""## Step 3 — Image Preprocessing
Preprocess uploaded image (resize, normalize if needed)

"""

def preprocess_image(image: Image.Image, target_size: int = 512) -> Image.Image:
    """
    Preprocess image:
    - Convert to RGB
    - Resize (maintain aspect ratio, pad to square)
    - Normalize
    """
    # Convert to RGB
    image = image.convert('RGB')

    # Resize maintaining aspect ratio
    w, h = image.size
    ratio = target_size / max(w, h)
    new_w = int(w * ratio)
    new_h = int(h * ratio)
    image = image.resize((new_w, new_h), Image.LANCZOS)

    # Pad to square
    square = Image.new('RGB', (target_size, target_size), (255, 255, 255))
    pad_x = (target_size - new_w) // 2
    pad_y = (target_size - new_h) // 2
    square.paste(image, (pad_x, pad_y))

    return square


def show_image_info(image: Image.Image, title: str = 'Image'):
    """Display image info and preview."""
    arr = np.array(image)
    print(f'[{title}]')
    print(f'  Size : {image.size[0]}x{image.size[1]}px')
    print(f'  Mode : {image.mode}')
    print(f'  Range: [{arr.min()}, {arr.max()}]')


print('✅ Preprocessing functions defined.')

"""## Step 4 — Segmentation

Use any method:
Pretrained model OR external API
Output should isolate:
Upper clothing OR lower clothing region

It detects 18 human body/clothing classes including:
- Upper: shirt, jacket, coat, dress, top
- Lower: pants, skirt, shorts, leggings
"""

# -------------------------------------------------------
# Load SegFormer - Human Parsing (ATR dataset, 18 classes)
# -------------------------------------------------------
MODEL_NAME = 'mattmdjaga/segformer_b2_clothes'

print(f'Loading segmentation model: {MODEL_NAME}')
print('This may take 1-2 minutes on first run...')

processor = SegformerImageProcessor.from_pretrained(MODEL_NAME)
seg_model = SegformerForSemanticSegmentation.from_pretrained(MODEL_NAME)
seg_model = seg_model.to(device)
seg_model.eval()

# ATR dataset label map
LABEL_MAP = {
    0:  'Background',
    1:  'Hat',
    2:  'Hair',
    3:  'Sunglasses',
    4:  'Upper-clothes',   # <-- upper body
    5:  'Skirt',           # <-- lower body
    6:  'Pants',           # <-- lower body
    7:  'Dress',           # <-- upper body (full)
    8:  'Belt',
    9:  'Left-shoe',
    10: 'Right-shoe',
    11: 'Face',
    12: 'Left-leg',
    13: 'Right-leg',
    14: 'Left-arm',
    15: 'Right-arm',
    16: 'Bag',
    17: 'Scarf'
}

# Which labels belong to upper / lower
UPPER_LABELS = [4, 7]          # Upper-clothes, Dress
LOWER_LABELS = [5, 6]          # Skirt, Pants

print(f'\n✅ Segmentation model loaded!')
print(f'   Labels: {len(LABEL_MAP)} classes')
print(f'   Upper body labels: {[LABEL_MAP[l] for l in UPPER_LABELS]}')
print(f'   Lower body labels: {[LABEL_MAP[l] for l in LOWER_LABELS]}')

"""## Segmentation Function"""

def segment_body_part(image: Image.Image, body_part: str) -> dict:
    """
    Segment upper or lower body clothing from image.

    Args:
        image     : PIL Image (preprocessed)
        body_part : 'upper' or 'lower'

    Returns:
        dict with:
          - 'mask'         : binary PIL Image (white=clothing, black=background)
          - 'segmap'       : full segmentation map array
          - 'labels_found' : list of detected clothing labels
          - 'coverage_pct' : % of image covered by the region
    """
    target_labels = UPPER_LABELS if body_part == 'upper' else LOWER_LABELS

    # Run SegFormer inference
    inputs = processor(images=image, return_tensors='pt').to(device)

    with torch.no_grad():
        outputs = seg_model(**inputs)

    # Upsample logits to original image size
    logits = outputs.logits  # shape: (1, num_labels, H/4, W/4)
    upsampled = torch.nn.functional.interpolate(
        logits,
        size=image.size[::-1],  # (H, W)
        mode='bilinear',
        align_corners=False
    )
    seg_map = upsampled.argmax(dim=1).squeeze().cpu().numpy()  # (H, W)

    # Build binary mask for target clothing labels
    binary_mask = np.zeros_like(seg_map, dtype=np.uint8)
    labels_found = []

    for label_id in target_labels:
        region = (seg_map == label_id)
        if region.sum() > 0:
            binary_mask[region] = 255
            labels_found.append(LABEL_MAP[label_id])

    # Dilate mask slightly for better inpainting coverage
    if binary_mask.sum() > 0:
        dilated = binary_dilation(binary_mask > 0, iterations=8).astype(np.uint8) * 255
        binary_mask = dilated

    # Smooth mask edges
    mask_pil = Image.fromarray(binary_mask)
    mask_pil = mask_pil.filter(ImageFilter.GaussianBlur(radius=3))
    mask_arr = np.array(mask_pil)
    mask_arr = (mask_arr > 127).astype(np.uint8) * 255
    mask_pil = Image.fromarray(mask_arr)

    total_pixels = seg_map.size
    coverage = (binary_mask > 0).sum() / total_pixels * 100

    return {
        'mask':          mask_pil,
        'segmap':        seg_map,
        'labels_found':  labels_found,
        'coverage_pct':  round(coverage, 1)
    }


print('✅ Segmentation function defined.')

"""## Visualization Helpers"""

def visualize_segmentation(image: Image.Image, seg_result: dict, body_part: str):
    """Show full segmentation map with all detected classes."""
    seg_map = seg_result['segmap']
    mask    = seg_result['mask']

    # Color palette for visualization
    palette = np.array([
        [0,0,0],[128,0,0],[0,128,0],[128,128,0],[0,0,128],
        [128,0,128],[0,128,128],[128,128,128],[64,0,0],[192,0,0],
        [64,128,0],[192,128,0],[64,0,128],[192,0,128],[64,128,128],
        [192,128,128],[0,64,0],[128,64,0]
    ], dtype=np.uint8)

    # Colorized seg map
    colored = palette[seg_map]

    fig, axes = plt.subplots(1, 4, figsize=(18, 5))
    fig.suptitle(f'Virtual Try-On Pipeline — {body_part.upper()} BODY', fontsize=14, fontweight='bold')

    axes[0].imshow(image)
    axes[0].set_title('1. Input Image', fontweight='bold')
    axes[0].axis('off')

    axes[1].imshow(colored)
    axes[1].set_title('2. Full Segmentation Map', fontweight='bold')
    axes[1].axis('off')

    # Add legend for detected classes
    unique_ids = np.unique(seg_map)
    legend_text = [f'{LABEL_MAP.get(i, str(i))}' for i in unique_ids if i in LABEL_MAP]
    axes[1].set_xlabel('Detected: ' + ', '.join(legend_text[:6]), fontsize=9)

    axes[2].imshow(mask, cmap='gray')
    axes[2].set_title(f'3. Binary Mask\n({body_part} region)', fontweight='bold')
    axes[2].axis('off')

    # Overlay: image + mask
    img_arr  = np.array(image).astype(float)
    mask_arr = np.array(mask).astype(float) / 255.0
    overlay = img_arr.copy()
    overlay[:,:,0] = np.clip(img_arr[:,:,0] * (1 - mask_arr*0.5) + 255*mask_arr*0.5, 0, 255)
    overlay[:,:,1] = np.clip(img_arr[:,:,1] * (1 - mask_arr*0.5), 0, 255)
    overlay[:,:,2] = np.clip(img_arr[:,:,2] * (1 - mask_arr*0.5), 0, 255)

    axes[3].imshow(overlay.astype(np.uint8))
    axes[3].set_title('4. Masked Overlay\n(region to replace)', fontweight='bold')
    axes[3].axis('off')

    plt.tight_layout()
    plt.savefig('/content/segmentation_result.png', dpi=150, bbox_inches='tight')
    plt.show()

    print(f'\n📊 Segmentation Summary')
    print(f'   Labels found : {seg_result["labels_found"] or ["None detected"]}')
    print(f'   Coverage     : {seg_result["coverage_pct"]}% of image')
    if not seg_result['labels_found']:
        print(f'   ⚠️  No {body_part} clothing detected — try a different image or body part.')


print('✅ Visualization helpers defined.')

"""## Step 5 — Hugging Face API Setup

Model used: `stabilityai/stable-diffusion-2-inpainting`
"""

# -----------------------------------------------
# Option A: Enter your HF token directly
# -----------------------------------------------
HF_TOKEN = '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'  # <-- paste your token here: hf_xxxxxxxxxxxx

# -----------------------------------------------
# Option B: Use Colab Secrets (recommended)
# -----------------------------------------------
# In Colab: click the 🔑 key icon (left sidebar) → add secret 'HF_TOKEN'
try:
    from google.colab import userdata
    if not HF_TOKEN:
        HF_TOKEN = userdata.get('HF_TOKEN')
        print('✅ Token loaded from Colab Secrets')
except Exception:
    pass

if HF_TOKEN:
    print(f'✅ HF Token set: {HF_TOKEN[:8]}...{HF_TOKEN[-4:]}')
else:
    print('⚠️  No HF token set — will use fallback simulation mode.')
    print('   For real inpainting, add your token above.')

"""## Step 6 — Inpainting (Important)

You must use an external AI API for inpainting.
Suggested platforms:
Hugging Face
*Segmind*
👉 You need to explore documentation and implement it yourself.

We are using Hugging Face Platforms used.
"""

# -------------------------------------------------------
# Approach 1: Hugging Face Inference API (Cloud)
# -------------------------------------------------------
HF_API_URL = 'https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-2-inpainting'

def image_to_bytes(image: Image.Image, fmt: str = 'PNG') -> bytes:
    buf = io.BytesIO()
    image.save(buf, format=fmt)
    return buf.getvalue()


def inpaint_with_hf_api(
    image:  Image.Image,
    mask:   Image.Image,
    prompt: str,
    token:  str,
    negative_prompt: str = 'blurry, distorted, deformed, low quality, ugly',
    num_inference_steps: int = 30,
    guidance_scale: float = 7.5
) -> Image.Image:
    """
    Call HF Inference API for inpainting.
    Uses multipart/form-data with image + mask + prompt.
    """
    print(f'🚀 Calling HF Inpainting API...')
    print(f'   Prompt: "{prompt}"')

    # Ensure both are 512x512
    image = image.resize((512, 512))
    mask  = mask.resize((512, 512))

    # Build request payload
    payload = {
        'inputs': prompt,
        'parameters': {
            'negative_prompt': negative_prompt,
            'num_inference_steps': num_inference_steps,
            'guidance_scale': guidance_scale
        }
    }

    files = {
        'image': ('image.png', image_to_bytes(image), 'image/png'),
        'mask_image': ('mask.png', image_to_bytes(mask), 'image/png'),
    }

    headers = {'Authorization': f'Bearer {token}'}

    # Some HF models use JSON payload only
    import base64
    def b64(img):
        return base64.b64encode(image_to_bytes(img)).decode()

    json_payload = {
        'inputs': prompt,
        'parameters': {
            'negative_prompt': negative_prompt,
            'num_inference_steps': num_inference_steps,
            'guidance_scale': guidance_scale,
            'image': b64(image),
            'mask_image': b64(mask)
        }
    }

    response = requests.post(
        HF_API_URL,
        headers=headers,
        json=json_payload,
        timeout=120
    )

    if response.status_code == 200:
        content_type = response.headers.get('content-type', '')
        if 'image' in content_type:
            result = Image.open(io.BytesIO(response.content))
            print(f'✅ Inpainting complete!')
            return result
        else:
            # Model might be loading
            data = response.json()
            raise RuntimeError(f'API returned non-image: {data}')

    elif response.status_code == 503:
        import time
        data = response.json()
        wait = data.get('estimated_time', 20)
        print(f'   Model loading, waiting {wait:.0f}s...')
        time.sleep(wait + 5)
        return inpaint_with_hf_api(image, mask, prompt, token, negative_prompt, num_inference_steps, guidance_scale)

    else:
        raise RuntimeError(f'HF API error {response.status_code}: {response.text[:200]}')


print('✅ HF API inpainting function defined.')

# -------------------------------------------------------
# Approach 2: Local Diffusers Pipeline (GPU required)
# -------------------------------------------------------
local_pipe = None  # lazy load

def load_local_pipeline():
    global local_pipe
    if local_pipe is not None:
        return local_pipe

    from diffusers import StableDiffusionInpaintPipeline
    print('Loading local SD inpainting pipeline (~5GB download)...')
    local_pipe = StableDiffusionInpaintPipeline.from_pretrained(
        'stabilityai/stable-diffusion-2-inpainting',
        torch_dtype=torch.float16 if device == 'cuda' else torch.float32
    ).to(device)
    local_pipe.enable_attention_slicing()  # memory optimization
    print('✅ Local pipeline loaded!')
    return local_pipe


def inpaint_local(
    image:  Image.Image,
    mask:   Image.Image,
    prompt: str,
    negative_prompt: str = 'blurry, distorted, deformed, low quality',
    num_steps: int = 30,
    guidance_scale: float = 7.5
) -> Image.Image:
    pipe = load_local_pipeline()
    image = image.resize((512, 512))
    mask  = mask.resize((512, 512))

    print(f'🚀 Running local inpainting — {num_steps} steps...')
    result = pipe(
        prompt=prompt,
        negative_prompt=negative_prompt,
        image=image,
        mask_image=mask,
        num_inference_steps=num_steps,
        guidance_scale=guidance_scale
    ).images[0]
    print('✅ Local inpainting complete!')
    return result


# -------------------------------------------------------
# Fallback: Simulation (no API / no GPU)
# -------------------------------------------------------
def inpaint_simulation(
    image:      Image.Image,
    mask:       Image.Image,
    prompt:     str,
    body_part:  str
) -> Image.Image:
    """
    Fallback simulation: color-blend the masked region
    based on keywords in the prompt.
    """
    color_map = {
        'black':  (30,  30,  30),
        'white':  (240, 240, 240),
        'red':    (192, 57,  43),
        'blue':   (41,  128, 185),
        'denim':  (58,  90,  137),
        'navy':   (26,  35,  126),
        'green':  (39,  174, 96),
        'grey':   (127, 140, 141),
        'gray':   (127, 140, 141),
        'yellow': (241, 196, 15),
        'pink':   (232, 67,  147),
        'purple': (142, 68,  173),
        'brown':  (121, 85,  72),
        'khaki':  (195, 176, 145),
        'orange': (230, 126, 34),
    }

    p_lower = prompt.lower()
    color = (100, 120, 180)  # default blue-grey
    for key, val in color_map.items():
        if key in p_lower:
            color = val
            break

    img_arr  = np.array(image.convert('RGB')).astype(float)
    mask_arr = np.array(mask.convert('L')).astype(float) / 255.0

    # Blend color into masked region
    result = img_arr.copy()
    for c, val in enumerate(color):
        result[:,:,c] = img_arr[:,:,c] * (1 - mask_arr * 0.7) + val * mask_arr * 0.7

    result_img = Image.fromarray(result.astype(np.uint8))

    # Add watermark
    draw = ImageDraw.Draw(result_img)
    draw.rectangle([0, result_img.height-26, result_img.width, result_img.height],
                   fill=(0, 0, 0, 180))
    draw.text((8, result_img.height-18),
              f'[SIMULATION] {prompt[:40]} | Add HF token for real results',
              fill=(255, 255, 100))

    return result_img


print('✅ All inpainting functions defined.')

"""## UI Requirement
Minimum:
Image upload
Selection option:
Upper / Lower
Button: “Try On”
Output image display
Optional (Bonus):
Build UI using:
- Gradio
- Streamlit

## Expected Pipeline
Upload Image → Segment Body Part → Apply Inpainting → Show Result

## Step 7 — Main Pipeline Function
"""

def virtual_tryon_system(
    image_input,
    body_part:   str   = 'upper',
    prompt:      str   = '',
    hf_token:    str   = '',
    use_local:   bool  = False,
    show_steps:  bool  = True
) -> dict:
    """
    Full Virtual Try-On System.

    Args:
        image_input : PIL Image or file path
        body_part   : 'upper' or 'lower'
        prompt      : clothing description (e.g. 'black leather jacket')
        hf_token    : Hugging Face API token (optional)
        use_local   : use local diffusers instead of API
        show_steps  : display intermediate results

    Returns:
        dict with 'result', 'mask', 'segmap', 'labels_found'
    """
    print('='*55)
    print(f' 👗 VIRTUAL TRY-ON SYSTEM')
    print(f'    Body part : {body_part.upper()}')
    print(f'    Prompt    : "{prompt}"')
    print('='*55)

    # --- Load image ---
    if isinstance(image_input, str):
        image = Image.open(image_input).convert('RGB')
    elif isinstance(image_input, np.ndarray):
        image = Image.fromarray(image_input)
    else:
        image = image_input.convert('RGB')

    # --- Step 1: Preprocess ---
    print('\n[1/4] Preprocessing image...')
    image = preprocess_image(image, target_size=512)
    show_image_info(image, 'Preprocessed')

    # --- Step 2: Segment ---
    print(f'\n[2/4] Segmenting {body_part} body clothing...')
    seg_result = segment_body_part(image, body_part)
    print(f'      Labels found : {seg_result["labels_found"] or ["None"]}')
    print(f'      Coverage     : {seg_result["coverage_pct"]}%')

    if show_steps:
        visualize_segmentation(image, seg_result, body_part)

    mask = seg_result['mask']

    # Warn if nothing detected
    if not seg_result['labels_found']:
        print(f'\n⚠️  No {body_part} clothing detected.')
        print('    Falling back to region-based mask...')
        # Simple fallback: use top or bottom half
        mask_arr = np.zeros((512, 512), dtype=np.uint8)
        if body_part == 'upper':
            mask_arr[80:300, 100:412] = 255
        else:
            mask_arr[300:480, 80:430] = 255
        mask = Image.fromarray(mask_arr)

    # Set default prompt
    if not prompt.strip():
        prompt = 'a stylish outfit, high quality fashion photo' if body_part == 'upper' \
                 else 'stylish pants, high quality fashion photo'

    full_prompt = f'photo of a person wearing {prompt}, photorealistic, high quality, fashion photo'

    # --- Step 3: Inpaint ---
    print(f'\n[3/4] Running AI inpainting...')
    print(f'      Full prompt: "{full_prompt}"')

    token = hf_token or HF_TOKEN

    if use_local:
        result = inpaint_local(image, mask, full_prompt)
    elif token:
        try:
            result = inpaint_with_hf_api(image, mask, full_prompt, token)
        except Exception as e:
            print(f'      ⚠️  HF API failed: {e}')
            print('      Falling back to simulation...')
            result = inpaint_simulation(image, mask, prompt, body_part)
    else:
        print('      ⚠️  No token — using simulation mode')
        result = inpaint_simulation(image, mask, prompt, body_part)

    result = result.resize((512, 512))

    # --- Step 4: Display ---
    print('\n[4/4] Displaying final result...')
    if show_steps:
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        fig.suptitle('Virtual Try-On — Final Output', fontsize=14, fontweight='bold')

        axes[0].imshow(image)
        axes[0].set_title('Original', fontweight='bold')
        axes[0].axis('off')

        axes[1].imshow(mask, cmap='gray')
        axes[1].set_title(f'{body_part.title()} Body Mask', fontweight='bold')
        axes[1].axis('off')

        axes[2].imshow(result)
        axes[2].set_title(f'Result: "{prompt[:30]}"', fontweight='bold')
        axes[2].axis('off')

        plt.tight_layout()
        plt.savefig('/content/tryon_result.png', dpi=150, bbox_inches='tight')
        plt.show()
        print('💾 Result saved to /content/tryon_result.png')

    print('\n✅ Pipeline complete!')

    return {
        'result':       result,
        'mask':         mask,
        'original':     image,
        'segmap':       seg_result['segmap'],
        'labels_found': seg_result['labels_found'],
        'coverage_pct': seg_result['coverage_pct']
    }


print('✅ Main pipeline function defined.')

"""## Step 8 — Test with a Sample Image

Download a test image of a person and run the pipeline.
"""

# Download a free sample fashion image
import urllib.request

sample_url = 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?w=512&q=80'
sample_path = '/content/sample_person.jpg'

print('Downloading sample image...')
urllib.request.urlretrieve(sample_url, sample_path)

sample_img = Image.open(sample_path)

print(f'✅ Sample image downloaded: {sample_img.size}')
plt.figure(figsize=(4, 5))
plt.imshow(sample_img)
plt.title('Sample Input Image')
plt.axis('off')
plt.show()

# -------------------------------------------------------
# RUN THE PIPELINE  — edit these values!
# -------------------------------------------------------

BODY_PART = 'upper'               # 'upper' or 'lower'
PROMPT    = 'black leather jacket'  # describe the clothing

# Run pipeline
output = virtual_tryon_system(
    image_input = sample_img,
    body_part   = BODY_PART,
    prompt      = PROMPT,
    show_steps  = True
)

"""## Step 9 — Upload Your Own Image"""

from google.colab import files

print('Upload a photo of a person:')
uploaded = files.upload()

if uploaded:
    fname = list(uploaded.keys())[0]
    user_image = Image.open(io.BytesIO(uploaded[fname]))
    print(f'✅ Uploaded: {fname} ({user_image.size})')

    # Show preview
    plt.figure(figsize=(4, 5))
    plt.imshow(user_image)
    plt.title(f'Uploaded: {fname}')
    plt.axis('off')
    plt.show()
else:
    print('No file uploaded.')

# Run pipeline on uploaded image
if 'user_image' in dir():
    output = virtual_tryon_system(
        image_input = user_image,
        body_part   = 'upper',      # change: 'upper' / 'lower'
        prompt      = 'red hoodie', # change: describe desired clothing
        show_steps  = True
    )

"""## Step 10 — Build UI using: Gradio

Launch a full web UI with upload, controls, and live output.
"""

def gradio_tryon(image, body_part, prompt):
    """Auto try-on without HF token input."""
    if image is None:
        return None, None, '❌ Please upload an image.'

    try:
        result = virtual_tryon_system(
            image_input=image,
            body_part=body_part.lower(),
            prompt=prompt,
            hf_token="",   # 👉 always empty = auto mode
            show_steps=False
        )

        status_lines = [
            '✅ Done!',
            f'Body part  : {body_part}',
            f'Clothing   : {prompt}',
            f'Labels found: {", ".join(result["labels_found"]) or "None (fallback mask used)"}',
            f'Coverage   : {result["coverage_pct"]}%',
            '🟡 Auto mode (no HF token required)'
        ]

        return (
            np.array(result['result']),
            np.array(result['mask'].convert('RGB')),
            '\n'.join(status_lines)
        )

    except Exception as e:
        import traceback
        return None, None, f'❌ Error: {str(e)}\n\n{traceback.format_exc()}'


# Build Gradio interface
with gr.Blocks(title='Virtual Try-On System', theme=gr.themes.Soft()) as demo:

    gr.Markdown("""
    # 👗 Virtual Try-On System
    **Pipeline:** Upload Image → Segment Body Part → AI Inpainting → Result
    """)

    with gr.Row():
        with gr.Column(scale=1):
            gr.Markdown('### Input')
            img_input = gr.Image(label='Upload image', type='pil')
            body_sel  = gr.Radio(
                choices=['Upper', 'Lower'],
                value='Upper',
                label='Body region'
            )
            prompt_in = gr.Textbox(
                label='Clothing prompt (bonus)',
                placeholder='e.g. black leather jacket, blue denim jeans...',
                value='black leather jacket'
            )
            run_btn = gr.Button('👗 Try On', variant='primary', size='lg')

        with gr.Column(scale=2):
            gr.Markdown('### Output')
            with gr.Row():
                mask_out   = gr.Image(label='Segmentation Mask', height=300)
                result_out = gr.Image(label='Final Result', height=300)
            status_out = gr.Textbox(label='Pipeline Status', lines=6, interactive=False)

    run_btn.click(
        fn=gradio_tryon,
        inputs=[img_input, body_sel, prompt_in],
        outputs=[result_out, mask_out, status_out]
    )

    gr.Examples(
        examples=[
            [sample_path, 'Upper', 'red hoodie'],
            [sample_path, 'Upper', 'white formal shirt'],
            [sample_path, 'Lower', 'blue denim jeans'],
            [sample_path, 'Lower', 'black dress pants'],
        ],
        inputs=[img_input, body_sel, prompt_in],
        label='Example inputs'
    )

demo.launch(share=True, debug=False)
print('🚀 Gradio UI launched! Click the public URL above.')

"""## Step 11 — Batch Mode (Test Multiple Prompts)"""

# Run multiple clothing prompts and compare results
TEST_PROMPTS = [
    ('upper', 'black leather jacket'),
    ('upper', 'white formal shirt'),
    ('upper', 'red hoodie'),
    ('lower', 'blue denim jeans'),
]

fig, axes = plt.subplots(2, len(TEST_PROMPTS)+1, figsize=(20, 9))
fig.suptitle('Batch Try-On Results', fontsize=16, fontweight='bold')

# Show original
orig = preprocess_image(sample_img)
for row in range(2):
    axes[row][0].imshow(orig)
    axes[row][0].set_title('Original', fontweight='bold')
    axes[row][0].axis('off')

for col, (body, prompt) in enumerate(TEST_PROMPTS):
    print(f'\nProcessing: [{body}] {prompt}')
    try:
        out = virtual_tryon_pipeline(sample_img, body, prompt, show_steps=False)
        axes[0][col+1].imshow(out['mask'], cmap='gray')
        axes[0][col+1].set_title(f'{body.title()}\nmask', fontsize=9)
        axes[0][col+1].axis('off')

        axes[1][col+1].imshow(out['result'])
        axes[1][col+1].set_title(f'{prompt[:20]}', fontsize=9, fontweight='bold')
        axes[1][col+1].axis('off')
    except Exception as e:
        print(f'   Error: {e}')
        axes[0][col+1].axis('off')
        axes[1][col+1].axis('off')

plt.tight_layout()
plt.savefig('/content/batch_results.png', dpi=150, bbox_inches='tight')
plt.show()
print('\n💾 Batch results saved to /content/batch_results.png')

"""## Step 12 — Download Results"""

# Download all result images
from google.colab import files

result_files = [
    '/content/tryon_result.png',
    '/content/segmentation_result.png',
    '/content/batch_results.png'
]

for f in result_files:
    if os.path.exists(f):
        print(f'Downloading {f}...')
        files.download(f)

print('\n✅ All results downloaded!')

"""---
## 📋 Short explanation of approach Summary

### Architecture
```
Input Image
    ↓
[Preprocessing]  PIL resize → 512×512 square, RGB normalize
    ↓
[Segmentation]   SegFormer-B2 (mattmdjaga/segformer_b2_clothes)
                 → 18-class human parsing on ATR dataset
                 → Upper labels: [Upper-clothes, Dress]
                 → Lower labels: [Pants, Skirt]
                 → Binary mask + dilation + Gaussian smoothing
    ↓
[Inpainting]     Stable Diffusion 2 Inpainting (stabilityai)
                 → Via HF Inference API or local diffusers
                 → Prompt: "photo of a person wearing {clothing}"
                 → Negative prompt: blurry, distorted, deformed
    ↓
Output Result
```

### Models Used
| Component | Model | Source |
|-----------|-------|--------|
| Segmentation | SegFormer-B2-Clothes | HuggingFace |
| Inpainting | SD 2 Inpainting | stabilityai / HF API |
| UI | Gradio | gradio.app |
"""